export {
  defineConfig,
  getActiveCheckerExtensions,
  getActiveCheckers,
  loadConfig,
  validateLiminaConfig,
  type BuiltinCheckerPreset,
  type BuiltinTaskName,
  type CheckerConfig,
  type CheckerExecutionKind,
  type CheckerPreset,
  type GraphConfig,
  type GraphRule,
  type GraphRuleAllowConfig,
  type GraphRuleDenyConfig,
  type GraphRuleDepDenyEntry,
  type GraphRuleRefAllowEntry,
  type GraphRuleRefDenyEntry,
  type LiminaCommand,
  type LiminaConfig,
  type LiminaConfigEnv,
  type LiminaConfigExport,
  type LiminaConfigFn,
  type LiminaConfigFnObject,
  type LiminaConfigFnPromise,
  type LoadConfigOptions,
  type PackageAttwCheckConfig,
  type PackageAttwProfile,
  type PackageBoundaryCheckConfig,
  type PackageCheckTool,
  type PackageCheckToolSelection,
  type PackageConfig,
  type PackageEntry,
  type PackagePublintCheckConfig,
  type PipelineStep,
  type ProofAllowlistEntry,
  type ProofConfig,
  type ResolvedCheckerConfig,
  type ResolvedLiminaConfig,
  type RuntimeEnvironment,
  type SharedLiminaConfig,
  type SourceBoundaryConfig,
  type SourceCheckConfig,
  type SourceUnusedDependenciesConfig,
  type SourceUnusedDependencyIgnoreEntry,
} from './config';

export {
  LiminaFlowReporter,
  createLiminaFlowReporter,
  type LiminaFlowFailureOptions,
  type LiminaFlowMessageOptions,
  type LiminaFlowOutputOptions,
  type LiminaFlowReporterOptions,
  type LiminaFlowTask,
} from './flow';

export {
  runGraphCheck,
  runGraphSync,
  type RunGraphCheckOptions,
  type RunGraphSyncOptions,
  type RunGraphSyncResult,
} from './commands/graph';
export {
  runInit,
  type RunInitOptions,
  type RunInitResult,
} from './commands/init';
export { runSourceCheck, type RunSourceCheckOptions } from './commands/source';
export {
  runCheckerBuild,
  runCheckerTypecheck,
  type RunCheckerBuildOptions,
  type RunCheckerBuildResult,
  type RunCheckerTypecheckOptions,
  type RunCheckerTypecheckResult,
  type TypecheckRunner,
  type TypecheckTarget,
  type TypecheckTargetResult,
} from './commands/typecheck';
export { isOrdinaryTypecheckConfigPath } from './tsconfig';
