export { defineConfig } from '#config/runner';
export {
  CancelledFailure,
  ConfigError as ConfigurationError,
  ExecutionFailure,
} from './domain/validation/errors';

export type {
  GovernanceIssue,
  GovernanceIssueEvidence,
  GovernanceIssueLocation,
  GovernanceIssueOrigin,
} from './domain/validation/issues';

export type { IssueSeverity } from './domain/validation/contracts';

export type {
  AutoCheckerConfig,
  BuildCheckerName,
  BuiltinTaskName,
  CheckerConfig,
  CheckerConfigMode,
  CheckerExecutionKind,
  CheckerName,
  CheckerScope,
  FrameworkCheckerName,
  GraphConditionDomain,
  GraphConfig,
  GraphRule,
  GraphRuleAllowConfig,
  GraphRuleDenyConfig,
  GraphRuleDependencyDenyEntry as GraphRuleDepDenyEntry,
  GraphRuleReferenceAllowEntry as GraphRuleRefAllowEntry,
  GraphRuleReferenceDenyEntry as GraphRuleRefDenyEntry,
  LiminaCommand,
  LiminaConfig,
  LiminaConfigEnvironment as LiminaConfigEnv,
  LiminaConfigExport,
  LiminaConfigFunction as LiminaConfigFn,
  LiminaConfigFunctionObject as LiminaConfigFnObject,
  LiminaConfigFunctionPromise as LiminaConfigFnPromise,
  PackageAttwCheckConfig,
  PackageAttwIgnoreRule,
  PackageAttwLevel,
  PackageAttwProfile,
  PackageBoundaryCheckConfig,
  PackageCheckTool,
  PackageCheckToolSelection,
  PackageConfig,
  PackageEntry,
  PackagePublintCheckConfig,
  PackagePublintLevel,
  PipelineStep,
  ProofAllowlistEntry,
  ProofConfig,
  RegionExcludeConfig,
  RegionExcludeKind,
  RegionsConfig,
  ReleaseConfig,
  ReleaseContentHashConfig,
  ReleaseContentHashConfigArguments as ReleaseContentHashConfigArgs,
  ReleaseNpmPackageJsonLintConfig,
  ReleaseNpmPackageJsonLintRuleConfig,
  ReleaseNpmPackageJsonLintSeverity,
  RuntimeEnvironment,
  SharedLiminaConfig,
  SourceAmbientDeclarationConfig,
  SourceBoundaryConfig,
  SourceCheckConfig,
  SourceDeclarationsConfig,
  SourceImportAuthorityConfig,
  SourceImportAuthorityWorkspaceRootGrant,
  SourceKnipCheckConfig,
  SourceKnipEntryConfig,
  SourceKnipIgnoredDependencyConfig,
  SourceKnipIgnoredFileConfig,
  SourceKnipWorkspaceConfig,
} from '#config/runner';
