export { defineConfig } from '#config/runner';
export {
  CancelledFailure,
  ConfigurationError,
  ExecutionFailure,
} from './domain/validation/errors';

export type {
  GovernanceIssue,
  GovernanceIssueEvidence,
  GovernanceIssueLocation,
  GovernanceIssueOrigin,
} from './domain/validation/issues';

export type { IssueSeverity } from './domain/validation/contracts';

export type {
  AutoCheckerConfig,
  BuildCheckerName,
  BuiltinTaskName,
  CheckerConfig,
  CheckerConfigMode,
  CheckerExecutionKind,
  CheckerName,
  CheckerScope,
  FrameworkCheckerName,
  GraphConditionDomain,
  GraphConfig,
  GraphRule,
  GraphRuleAllowConfig,
  GraphRuleDenyConfig,
  GraphRuleDepDenyEntry,
  GraphRuleRefAllowEntry,
  GraphRuleRefDenyEntry,
  LiminaCommand,
  LiminaConfig,
  LiminaConfigEnv,
  LiminaConfigExport,
  LiminaConfigFn,
  LiminaConfigFnObject,
  LiminaConfigFnPromise,
  PackageAttwCheckConfig,
  PackageAttwIgnoreRule,
  PackageAttwLevel,
  PackageAttwProfile,
  PackageBoundaryCheckConfig,
  PackageCheckTool,
  PackageCheckToolSelection,
  PackageConfig,
  PackageEntry,
  PackagePublintCheckConfig,
  PackagePublintLevel,
  PipelineStep,
  ProofAllowlistEntry,
  ProofConfig,
  RegionExcludeConfig,
  RegionExcludeKind,
  RegionsConfig,
  ReleaseConfig,
  ReleaseContentHashConfig,
  ReleaseContentHashConfigArgs,
  ReleaseNpmPackageJsonLintConfig,
  ReleaseNpmPackageJsonLintRuleConfig,
  ReleaseNpmPackageJsonLintSeverity,
  RuntimeEnvironment,
  SharedLiminaConfig,
  SourceAmbientDeclarationConfig,
  SourceBoundaryConfig,
  SourceCheckConfig,
  SourceDeclarationsConfig,
  SourceImportAuthorityConfig,
  SourceImportAuthorityWorkspaceRootGrant,
  SourceKnipCheckConfig,
  SourceKnipEntryConfig,
  SourceKnipIgnoredDependencyConfig,
  SourceKnipIgnoredFileConfig,
  SourceKnipWorkspaceConfig,
} from '#config/runner';
