import recordings from './command-transcripts.json';

export interface CommandTranscript {
  id: string;
  command: string;
  workspace: string;
  exitCode: number;
  lines: readonly string[];
}

// Generated by scripts/docs/capture-command-transcripts.ts from the built CLI.
export const commandTranscripts: Record<string, CommandTranscript> =
  recordings.commands;
