// Captured from the built CLI of the current tracked staged/unstaged snapshot.
// Source snapshot SHA-256: 4182729f32b9e5881b2ecd4c3bfde0cb018b04e0567d3c5e256a83a72d904ae1.
// Isolated two-package fixture, TypeScript 6.0.3; counts and durations vary.
// Blank lines, box borders, invocation IDs, and local query paths are omitted.
export interface DemoTranscript {
  id: string;
  command: string;
  workspace: string;
  exitCode: number;
  lines: readonly string[];
}

export const demoTranscripts: Record<string, DemoTranscript> = {
  prepare: {
    id: 'prepare',
    command: 'pnpm exec limina graph prepare',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina graph prepare',
      'limina[task.graph]: graph prepare started',
      '[start] graph prepare',
      'limina[task.graph]: graph prepare generated files',
      '[pass] graph prepare (1.54s)',
      '[done] limina graph passed',
    ],
  },
  build: {
    id: 'build',
    command: 'pnpm exec limina checker build',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina checker build',
      '[start] checker build',
      '  [info] found 1 checker build entry(s)',
      'limina[task.typecheck]: Running build checks for 1 checker entry(s).',
      'CWD: .',
      'Entries: .limina/tsconfig/checkers/tsc/tsconfig.build.json',
      '  [start] tsc -b .limina/tsconfig/checkers/tsc/tsconfig.build.json',
      '  [pass] tsc -b .limina/tsconfig/checkers/tsc/tsconfig.build.json (315ms)',
      'limina[task.typecheck]: Checked 1 checker build entry(s).',
      'limina[task.typecheck]: checker build finished',
      '[pass] checker build (4.90s)',
      '[done] limina checker passed',
    ],
  },
  incremental: {
    id: 'incremental',
    command: 'pnpm exec limina checker build',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina checker build',
      '[start] checker build',
      '  [info] found 1 checker build entry(s)',
      'limina[task.typecheck]: Running build checks for 1 checker entry(s).',
      'CWD: .',
      'Entries: .limina/tsconfig/checkers/tsc/tsconfig.build.json',
      '  [start] tsc -b .limina/tsconfig/checkers/tsc/tsconfig.build.json',
      '  [pass] tsc -b .limina/tsconfig/checkers/tsc/tsconfig.build.json (71ms)',
      'limina[task.typecheck]: Checked 1 checker build entry(s).',
      'limina[task.typecheck]: checker build finished',
      '[pass] checker build (1.71s)',
      '[done] limina checker passed',
    ],
  },
  graph: {
    id: 'graph',
    command: 'pnpm exec limina graph check',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina graph check',
      '[start] graph check',
      'limina[task.graph]: Checked 2 graph projects; references are valid.',
      'limina[task.graph]: graph check finished',
      '[pass] graph check (1.57s)',
      '[done] limina graph passed',
    ],
  },
  source: {
    id: 'source',
    command: 'pnpm exec limina source check',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina source check',
      '[start] source check',
      'limina[task.source]: Checked 2 source project owners; package scopes are valid.',
      'limina[task.source]: source check finished',
      '[pass] source check (1.73s)',
      '[done] limina source passed',
    ],
  },
  proof: {
    id: 'proof',
    command: 'pnpm exec limina proof check',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina proof check',
      '[start] proof check',
      'limina[task.proof]: Checked 2 checker entry projects and 2 dts configs.',
      'Graph-capable checker entries cover 2 files; checker entries cover 2 files.',
      'Configured source boundary covers 2 files.',
      'limina[task.proof]: proof check finished',
      '[pass] proof check (1.41s)',
      '[done] limina proof passed',
    ],
  },
  check: {
    id: 'check',
    command: 'pnpm exec limina check',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina check',
      '[start] default check',
      '  [start] workspace validate',
      '  [pass] workspace validate (13ms)',
      '  [start] graph materialize',
      '  [pass] graph materialize (1.61s)',
      '  [start] graph check',
      '  [start] proof check',
      '  [start] checker build',
      '  [start] checker typecheck',
      '    [start] source graph routes',
      '    [pass] source graph routes (0ms)',
      '    [start] project references',
      '    [pass] project references (10ms)',
      '    [start] condition domains',
      '    [pass] condition domains (1ms)',
      '    [start] reference completeness',
      '    [pass] reference completeness (470ms)',
      '    [start] project routes and configs',
      '    [pass] project routes and configs (16ms)',
      '    [start] checker coverage targets',
      '    [pass] checker coverage targets (0ms)',
      '  [pass] graph check (543ms)',
      '    [start] proof allowlist',
      '    [pass] proof allowlist (0ms)',
      '    [start] source coverage',
      '    [pass] source coverage (2ms)',
      '  [pass] proof check (553ms)',
      '  [skip] checker typecheck (disabled) (990ms)',
      '    [start] tsc -b .limina/tsconfig/checkers/tsc/tsconfig.build.json',
      '    [pass] tsc -b .limina/tsconfig/checkers/tsc/tsconfig.build.json (74ms)',
      '  [pass] checker build (1.54s)',
      '  [start] source check',
      '    [start] source graph routes',
      '    [pass] source graph routes (0ms)',
      '    [start] tsconfig governance',
      '    [pass] tsconfig governance (3ms)',
      '    [start] knip source usage',
      '    [skip] source.knip is disabled (0ms)',
      '    [start] source project ownership',
      '    [pass] source project ownership (0ms)',
      '    [start] source import authority',
      '    [pass] source import authority (5ms)',
      '  [pass] source check (18ms)',
      '[pass] default check (3.25s)',
      '[done] limina check passed',
      ' Command: limina check',
      ' Config: limina.config.mjs',
      ' Duration: 3.2s',
      ' Executed tasks: 5 / 5',
      ' Passed tasks: 4 / 5',
      ' Open issues: 0',
      ' Validation units:',
      ' ✓ graph:check                   units 99  issues  0  543ms',
      '   ✓ source graph routes         units  2  issues  0  0ms',
      '   ✓ project references          units 93  issues  0  10ms',
      '   ✓ condition domains           units  2  issues  0  1ms',
      '   ✓ reference completeness      units  2  issues  0  470ms',
      ' ✓ source:check                  units 13  issues  0  18ms',
      '   ✓ source graph routes         units  2  issues  0  0ms',
      '   ✓ tsconfig governance         units  6  issues  0  3ms',
      '   ◇ knip source usage           units  0  issues  0  0ms',
      '   ✓ source project ownership    units  4  issues  0  0ms',
      '   ✓ source import authority     units  1  issues  0  5ms',
      ' ✓ proof:check                   units  9  issues  0  553ms',
      '   ✓ project routes and configs  units  6  issues  0  16ms',
      '   ✓ checker coverage targets    units  1  issues  0  0ms',
      '   ✓ proof allowlist             units  0  issues  0  0ms',
      '   ✓ source coverage             units  2  issues  0  2ms',
      ' ✓ checker:build                 units  1  issues  0  1.5s',
      '   ✓ tsc checker entry           units  1  issues  0  74ms',
    ],
  },
  pipeline: {
    id: 'pipeline',
    command: 'pnpm exec limina check release',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina check',
      '[start] pipeline: release',
      '  [start] command: pnpm build',
      '    [start] command execution',
      'Scope: all 3 workspace projects',
      'Done in 393ms using pnpm v11.28.3',
      '    [pass] command execution (924ms)',
      '  [pass] command: pnpm build (925ms)',
      '  [start] workspace validate',
      '  [pass] workspace validate (20ms)',
      '  [start] package check',
      'limina[task.package]: Package check plan:',
      '  config: limina.config.mjs',
      '  cwd: packages/core',
      '  selection: activated workspace package "@demo/core" matched configured package entry name.',
      '  entries:',
      '    - @demo/core',
      '      outDir: packages/core/dist',
      '      checks: publint, attw, boundary',
      '    [start] @demo/core (publint, attw, boundary)',
      '      [start] package tarball: @demo/core',
      'limina[task.package]: package tarball packing started: @demo/core',
      'limina[task.package]: package tarball packed: @demo/core',
      '      [pass] package tarball: @demo/core (415ms)',
      '      [start] publint: @demo/core',
      'limina[task.package]: publint started: @demo/core',
      'limina[task.package]: publint passed: @demo/core',
      '      [pass] publint: @demo/core (22ms)',
      '      [start] attw: @demo/core',
      'limina[task.package]: attw started: @demo/core (profile: esm-only)',
      'limina[task.package]: attw passed: @demo/core',
      '      [pass] attw: @demo/core (130ms)',
      '      [start] package boundary: @demo/core',
      'limina[task.package]: package boundary started: @demo/core',
      'limina[task.package]: package boundary passed: @demo/core',
      '      [pass] package boundary: @demo/core (3ms)',
      'limina[task.package]: package checks passed: @demo/core',
      '    [pass] @demo/core (publint, attw, boundary) (586ms)',
      '  [pass] package check (588ms)',
      '  [start] release check',
      'limina[task.release]: Release check plan:',
      '  config: limina.config.mjs',
      '  cwd: packages/core',
      '  selection: activated workspace package "@demo/core" matched configured package entry name.',
      '  entries:',
      '    - @demo/core',
      '      outDir: packages/core/dist',
      '    [start] @demo/core',
      '    [start] release tarball: @demo/core',
      'limina[task.release]: release tarball packing started: @demo/core',
      'limina[task.release]: release tarball packed: @demo/core',
      '    [pass] release tarball: @demo/core (760ms)',
      'limina[task.release]: release checks passed: @demo/core',
      '    [pass] @demo/core (764ms)',
      '  [pass] release check (769ms)',
      '[pass] pipeline: release (2.38s)',
      '[done] limina check passed',
      ' Command: limina check release',
      ' Config: limina.config.mjs',
      ' Duration: 2.3s',
      ' Executed tasks: 3 / 3',
      ' Passed tasks: 3 / 3',
      ' Open issues: 0',
      ' Validation units:',
      ' ✓ pnpm build                              units 1  issues 0  925ms',
      '   ✓ command execution                     units 1  issues 0  924ms',
      ' ✓ package:check                           units 3  issues 0  588ms',
      '   ✓ @demo/core (publint, attw, boundary)  units 3  issues 0  586ms',
      ' ✓ release:check                           units 1  issues 0  769ms',
      '   ✓ @demo/core                            units 1  issues 0  764ms',
      '$ node build.mjs',
    ],
  },
  boundary: {
    id: 'boundary',
    command: 'pnpm exec limina source check',
    workspace: 'limina-demo',
    exitCode: 1,
    lines: [
      '[start] limina source check',
      '[start] source check',
      '[fail] source check failed (2.26s)',
      '[done] limina source failed',
      ' Found 1 source check issue in 1 package.',
      ' Relative import escapes package scope  1 issue',
      ' package: @demo/app',
      ' rule: LIMINA_SOURCE_RELATIVE_IMPORT_ESCAPES_SCOPE',
      ' package manifest: packages/app/package.json',
      ' detector: source',
      ' tool: limina',
      ' summary:',
      '   Relative import escapes package scope',
      ' reason:',
      '   relative source imports must not cross the nearest package.json package boundary.',
      ' verify:',
      '   - limina source check',
      ' evidence:',
      '   - diagnostic',
      '     Relative import escapes package scope:',
      '       source owner: packages/app/package.json',
      '       package scope: packages/app/package.json',
      '       file: packages/app/src/index.ts:1 (kind: static)',
      '       imported specifier: ../../core/src/index.js',
      '       resolved file: packages/core/src/index.ts',
      '       target package scope: packages/core/package.json',
      '       reason: relative source imports must not cross the nearest package.json',
      '               package boundary.',
      ' files:',
      '   - packages/app/src/index.ts',
    ],
  },
};
