// Recorded from isolated fixtures using Limina source at bfe3bfa2.
// Messages, task states, counts, and durations come from captured CLI output.
// Blank lines and box borders are omitted; local query paths are excluded.
export interface DemoTranscript {
  id: string;
  command: string;
  workspace: string;
  exitCode: number;
  lines: readonly string[];
}

export const demoTranscripts: Record<string, DemoTranscript> = {
  prepare: {
    id: 'prepare',
    command: 'pnpm exec limina graph prepare',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina graph prepare',
      'limina[task.graph]: graph prepare started',
      '[start] graph prepare',
      'limina[task.graph]: graph prepare generated files',
      '[pass] graph prepare (704ms)',
      '[done] limina graph passed',
    ],
  },
  build: {
    id: 'build',
    command: 'pnpm exec limina checker build',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina checker build',
      '[start] checker build',
      '  [info] found 1 checker build entry(s)',
      'limina[task.typecheck]: Running build checks for 1 checker entry(s).',
      'CWD: .',
      'Entries: .limina/tsconfig/checkers/tsc/tsconfig.build.json',
      '  [start] tsc -b .limina/tsconfig/checkers/tsc/tsconfig.build.json',
      '  [pass] tsc -b .limina/tsconfig/checkers/tsc/tsconfig.build.json (307ms)',
      'limina[task.typecheck]: Checked 1 checker build entry(s).',
      'limina[task.typecheck]: checker build finished',
      '[pass] checker build (1.46s)',
      '[done] limina checker passed',
    ],
  },
  incremental: {
    id: 'incremental',
    command: 'pnpm exec limina checker build',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina checker build',
      '[start] checker build',
      '  [info] found 1 checker build entry(s)',
      'limina[task.typecheck]: Running build checks for 1 checker entry(s).',
      'CWD: .',
      'Entries: .limina/tsconfig/checkers/tsc/tsconfig.build.json',
      '  [start] tsc -b .limina/tsconfig/checkers/tsc/tsconfig.build.json',
      '  [pass] tsc -b .limina/tsconfig/checkers/tsc/tsconfig.build.json (69ms)',
      'limina[task.typecheck]: Checked 1 checker build entry(s).',
      'limina[task.typecheck]: checker build finished',
      '[pass] checker build (1.16s)',
      '[done] limina checker passed',
    ],
  },
  graph: {
    id: 'graph',
    command: 'pnpm exec limina graph check',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina graph check',
      '[start] graph check',
      'limina[task.graph]: Checked 2 graph projects; references are valid.',
      'limina[task.graph]: graph check finished',
      '[pass] graph check (978ms)',
      '[done] limina graph passed',
    ],
  },
  source: {
    id: 'source',
    command: 'pnpm exec limina source check',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina source check',
      '[start] source check',
      'limina[task.source]: Checked 2 source project owners; package scopes are valid.',
      'limina[task.source]: source check finished',
      '[pass] source check (884ms)',
      '[done] limina source passed',
    ],
  },
  proof: {
    id: 'proof',
    command: 'pnpm exec limina proof check',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina proof check',
      '[start] proof check',
      'limina[task.proof]: Checked 2 checker entry projects and 2 dts configs.',
      'Graph-capable checker entries cover 2 files; checker entries cover 2 files.',
      'Configured source boundary covers 2 files.',
      'limina[task.proof]: proof check finished',
      '[pass] proof check (656ms)',
      '[done] limina proof passed',
    ],
  },
  check: {
    id: 'check',
    command: 'pnpm exec limina check',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina check',
      '[start] default check',
      '  [start] workspace validate',
      '  [pass] workspace validate (16ms)',
      '  [start] graph materialize',
      '  [pass] graph materialize (676ms)',
      '  [start] graph check',
      '  [start] proof check',
      '  [start] checker build',
      '  [start] checker typecheck',
      '    [start] source graph routes',
      '    [pass] source graph routes (0ms)',
      '    [start] project references',
      '    [pass] project references (4ms)',
      '    [start] condition domains',
      '    [pass] condition domains (0ms)',
      '    [start] reference completeness',
      '    [pass] reference completeness (389ms)',
      '    [start] project routes and configs',
      '    [pass] project routes and configs (8ms)',
      '    [start] checker coverage targets',
      '    [pass] checker coverage targets (0ms)',
      '  [pass] graph check (413ms)',
      '    [start] proof allowlist',
      '    [pass] proof allowlist (0ms)',
      '    [start] source coverage',
      '    [pass] source coverage (2ms)',
      '  [pass] proof check (434ms)',
      '  [skip] checker typecheck (disabled) (527ms)',
      '    [start] tsc -b .limina/tsconfig/checkers/tsc/tsconfig.build.json',
      '    [pass] tsc -b .limina/tsconfig/checkers/tsc/tsconfig.build.json (76ms)',
      '  [pass] checker build (943ms)',
      '  [start] source check',
      '    [start] source graph routes',
      '    [pass] source graph routes (0ms)',
      '    [start] tsconfig governance',
      '    [pass] tsconfig governance (4ms)',
      '    [start] knip source usage',
      '    [skip] source.knip is disabled (0ms)',
      '    [start] source project ownership',
      '    [pass] source project ownership (0ms)',
      '    [start] source import authority',
      '    [pass] source import authority (5ms)',
      '  [pass] source check (17ms)',
      '[pass] default check (1.73s)',
      '[done] limina check passed',
      'Limina check summary',
      'Command: limina check',
      'Config: limina.config.mjs',
      'Duration: 1.7s',
      'Executed tasks: 5 / 5',
      'Passed tasks: 4 / 5',
      'Open issues: 0',
      'Validation units:',
      '✓ graph:check                   units 99  issues  0  413ms',
      '  ✓ source graph routes         units  2  issues  0  0ms',
      '  ✓ project references          units 93  issues  0  4ms',
      '  ✓ condition domains           units  2  issues  0  0ms',
      '  ✓ reference completeness      units  2  issues  0  389ms',
      '✓ source:check                  units 13  issues  0  17ms',
      '  ✓ source graph routes         units  2  issues  0  0ms',
      '  ✓ tsconfig governance         units  6  issues  0  4ms',
      '  ◇ knip source usage           units  0  issues  0  0ms',
      '  ✓ source project ownership    units  4  issues  0  0ms',
      '  ✓ source import authority     units  1  issues  0  5ms',
      '✓ proof:check                   units  9  issues  0  434ms',
      '  ✓ project routes and configs  units  6  issues  0  8ms',
      '  ✓ checker coverage targets    units  1  issues  0  0ms',
      '  ✓ proof allowlist             units  0  issues  0  0ms',
      '  ✓ source coverage             units  2  issues  0  2ms',
      '✓ checker:build                 units  1  issues  0  943ms',
      '  ✓ tsc checker entry           units  1  issues  0  76ms',
    ],
  },
  pipeline: {
    id: 'pipeline',
    command: 'pnpm --dir packages/core exec limina check release',
    workspace: 'limina-demo',
    exitCode: 0,
    lines: [
      '[start] limina check',
      '[start] pipeline: release',
      '  [start] command: pnpm build',
      '    [start] command execution',
      '    [pass] command execution (600ms)',
      '  [pass] command: pnpm build (601ms)',
      '  [start] workspace validate',
      '  [pass] workspace validate (16ms)',
      '  [start] package check',
      'limina[task.package]: Package check plan:',
      '  config: limina.config.mjs',
      '  cwd: packages/core',
      '  selection: activated workspace package "@demo/core" matched configured package entry name.',
      '  entries:',
      '    - @demo/core',
      '      outDir: packages/core/dist',
      '      checks: publint, attw, boundary',
      '    [start] @demo/core (publint, attw, boundary)',
      '      [start] package tarball: @demo/core',
      'limina[task.package]: package tarball packing started: @demo/core',
      'limina[task.package]: package tarball packed: @demo/core',
      '      [pass] package tarball: @demo/core (310ms)',
      '      [start] publint: @demo/core',
      'limina[task.package]: publint started: @demo/core',
      'limina[task.package]: publint passed: @demo/core',
      '      [pass] publint: @demo/core (25ms)',
      '      [start] attw: @demo/core',
      'limina[task.package]: attw started: @demo/core (profile: esm-only)',
      'limina[task.package]: attw passed: @demo/core',
      '      [pass] attw: @demo/core (70ms)',
      '      [start] package boundary: @demo/core',
      'limina[task.package]: package boundary started: @demo/core',
      'limina[task.package]: package boundary passed: @demo/core',
      '      [pass] package boundary: @demo/core (2ms)',
      'limina[task.package]: package checks passed: @demo/core',
      '    [pass] @demo/core (publint, attw, boundary) (410ms)',
      '  [pass] package check (411ms)',
      '  [start] release check',
      'limina[task.release]: Release check plan:',
      '  config: limina.config.mjs',
      '  cwd: packages/core',
      '  selection: activated workspace package "@demo/core" matched configured package entry name.',
      '  entries:',
      '    - @demo/core',
      '      outDir: packages/core/dist',
      '    [start] @demo/core',
      '    [start] release tarball: @demo/core',
      'limina[task.release]: release tarball packing started: @demo/core',
      'limina[task.release]: release tarball packed: @demo/core',
      '    [pass] release tarball: @demo/core (315ms)',
      'limina[task.release]: release checks passed: @demo/core',
      '    [pass] @demo/core (317ms)',
      '  [pass] release check (320ms)',
      '[pass] pipeline: release (1.42s)',
      '[done] limina check passed',
      'Limina check summary',
      'Command: limina check release',
      'Config: limina.config.mjs',
      'Duration: 1.4s',
      'Executed tasks: 3 / 3',
      'Passed tasks: 3 / 3',
      'Open issues: 0',
      'Validation units:',
      '✓ pnpm build                              units 1  issues 0  601ms',
      '  ✓ command execution                     units 1  issues 0  601ms',
      '✓ package:check                           units 3  issues 0  411ms',
      '  ✓ @demo/core (publint, attw, boundary)  units 3  issues 0  410ms',
      '✓ release:check                           units 1  issues 0  320ms',
      '  ✓ @demo/core                            units 1  issues 0  317ms',
    ],
  },
  boundary: {
    id: 'boundary',
    command: 'pnpm exec limina source check',
    workspace: 'limina-demo-boundary',
    exitCode: 1,
    lines: [
      '[start] limina source check',
      '[start] source check',
      '[fail] source check failed (962ms)',
      '[done] limina source failed',
      'Source check summary',
      'Found 1 source check issue in 1 package.',
      'Relative import escapes package scope  1 issue',
      'package: @demo/app',
      'rule: LIMINA_SOURCE_RELATIVE_IMPORT_ESCAPES_SCOPE',
      'package manifest: packages/app/package.json',
      'detector: source',
      'tool: limina',
      '',
      'summary:',
      '  Relative import escapes package scope',
      '',
      'reason:',
      '  relative source imports must not cross the nearest package.json package boundary.',
      '',
      'verify:',
      '  - limina source check',
      '',
      'evidence:',
      '  - diagnostic',
      '    Relative import escapes package scope:',
      '      source owner: packages/app/package.json',
      '      package scope: packages/app/package.json',
      '      file: packages/app/src/index.ts:1 (kind: static)',
      '      imported specifier: ../../core/src/index',
      '      resolved file: packages/core/src/index.ts',
      '      target package scope: packages/core/package.json',
      '      reason: relative source imports must not cross the nearest package.json',
      '              package boundary.',
      '',
      'files:',
      '  - packages/app/src/index.ts',
    ],
  },
};
