import { parse, type ParseError } from 'jsonc-parser';
import { describe, expect, it } from 'vitest';
import { deleteJsoncProperty } from '../commands/migration/jsonc-delete';

function removeProperty(
  content: string,
  path: readonly (number | string)[],
): string {
  const result = deleteJsoncProperty(content, path);
  const errors: ParseError[] = [];
  parse(result, errors, { allowTrailingComma: true });
  expect(errors).toEqual([]);
  return result;
}

describe('deleteJsoncProperty', () => {
  it.each([
    {
      expected: '{\n  "strict": true,\n  "isolatedModules": true\n}\n',
      name: 'middle property with a trailing comma',
      path: ['declaration'],
      source:
        '{\n  "strict": true,\n  "declaration": true,\n  "isolatedModules": true\n}\n',
    },
    {
      expected: '{\n  "strict": true\n}\n',
      name: 'first property',
      path: ['declaration'],
      source: '{\n  "declaration": true,\n  "strict": true\n}\n',
    },
    {
      expected: '{\n  "strict": true\n}\n',
      name: 'last property without a trailing comma',
      path: ['declaration'],
      source: '{\n  "strict": true,\n  "declaration": true\n}\n',
    },
    {
      expected: '{\n  "strict": true,\n}\n',
      name: 'last property with a trailing comma',
      path: ['declaration'],
      source: '{\n  "strict": true,\n  "declaration": true,\n}\n',
    },
    {
      expected: '{\n}\n',
      name: 'only property without a trailing comma',
      path: ['declaration'],
      source: '{\n  "declaration": true\n}\n',
    },
    {
      expected: '{\n}\n',
      name: 'only property with a trailing comma',
      path: ['declaration'],
      source: '{\n  "declaration": true,\n}\n',
    },
    {
      expected: '{\n  "include": []\n}\n',
      name: 'whole compilerOptions property',
      path: ['compilerOptions'],
      source:
        '{\n  "compilerOptions": {\n    "declaration": true\n  },\n  "include": []\n}\n',
    },
    {
      expected: '{\n  "include": []\n}\n',
      name: 'last references property',
      path: ['references'],
      source:
        '{\n  "include": [],\n  "references": [\n    {"path": "./lib"}\n  ]\n}\n',
    },
  ])(
    'deletes a $name without changing JSONC validity',
    ({ expected, path, source }) => {
      expect(removeProperty(source, path)).toBe(expected);
    },
  );

  it('deletes consecutive line properties without leaving blank lines', () => {
    const source =
      '{\n  "compilerOptions": {\n    "declaration": true,\n    "outDir": "./dist",\n    "noEmit": false,\n    "isolatedModules": true\n  }\n}\n';
    let result = source;
    for (const field of ['declaration', 'outDir', 'noEmit']) {
      result = deleteJsoncProperty(result, ['compilerOptions', field]);
    }

    expect(result).toBe(
      '{\n  "compilerOptions": {\n    "isolatedModules": true\n  }\n}\n',
    );
    expect(result).not.toMatch(/"compilerOptions": \{\r?\n(?:[ \t]*\r?\n)+/u);
    removeProperty(result, ['compilerOptions', 'isolatedModules']);
  });

  it('preserves an intentional blank line before a deleted property', () => {
    const source =
      '{\n  "strict": true,\n\n  "declaration": true,\n  "isolatedModules": true\n}\n';

    expect(removeProperty(source, ['declaration'])).toBe(
      '{\n  "strict": true,\n\n  "isolatedModules": true\n}\n',
    );
  });

  it('keeps compact inline JSONC compact', () => {
    const source = '{"strict":true,"declaration":true,"isolatedModules":true}';

    expect(removeProperty(source, ['declaration'])).toBe(
      '{"strict":true,"isolatedModules":true}',
    );
  });

  it('preserves inline trivia while removing a last property', () => {
    const source = '{"strict":true, "declaration":true}';

    expect(removeProperty(source, ['declaration'])).toBe('{"strict":true }');
  });

  it('preserves CRLF line endings and tab indentation', () => {
    const source = '{\r\n\t"strict": true,\r\n\t"declaration": true\r\n}\r\n';

    expect(removeProperty(source, ['declaration'])).toBe(
      '{\r\n\t"strict": true\r\n}\r\n',
    );
  });

  it('deletes an attached line comment with its property', () => {
    const source =
      '{\n  "strict": true,\n  // generated by the declaration build\n  "declaration": true,\n  "isolatedModules": true\n}\n';

    expect(removeProperty(source, ['declaration'])).toBe(
      '{\n  "strict": true,\n  "isolatedModules": true\n}\n',
    );
  });

  it('deletes an attached block comment with its property', () => {
    const source =
      '{\n  /* generated by the declaration build */\n  "declaration": true,\n  "isolatedModules": true\n}\n';

    expect(removeProperty(source, ['declaration'])).toBe(
      '{\n  "isolatedModules": true\n}\n',
    );
  });

  it('deletes an attached multiline block comment with its property', () => {
    const source =
      '{\n  /*\n   * generated by the declaration build\n   */\n  "declaration": true,\n  "isolatedModules": true\n}\n';

    expect(removeProperty(source, ['declaration'])).toBe(
      '{\n  "isolatedModules": true\n}\n',
    );
  });

  it('preserves a comment separated from the property by a blank line', () => {
    const source =
      '{\n  // general compiler policy\n\n  "declaration": true\n}\n';

    expect(removeProperty(source, ['declaration'])).toBe(
      '{\n  // general compiler policy\n\n}\n',
    );
  });

  it('does not consume the previous sibling comment', () => {
    const source =
      '{\n  // strict mode rationale\n  "strict": true,\n  "declaration": true\n}\n';

    expect(removeProperty(source, ['declaration'])).toBe(
      '{\n  // strict mode rationale\n  "strict": true\n}\n',
    );
  });

  it('preserves a previous sibling trailing comment', () => {
    const source =
      '{\n  "strict": true, // strict mode rationale\n  "declaration": true\n}\n';

    expect(removeProperty(source, ['declaration'])).toBe(
      '{\n  "strict": true // strict mode rationale\n}\n',
    );
  });

  it.each([
    {
      name: 'middle property with a trailing line comment',
      source:
        '{\n  "strict": true,\n  "declaration": true, // generated\n  "isolatedModules": true\n}\n',
      expected: '{\n  "strict": true,\n  "isolatedModules": true\n}\n',
    },
    {
      name: 'last property without a trailing comma and with a line comment',
      source: '{\n  "strict": true,\n  "declaration": true // generated\n}\n',
      expected: '{\n  "strict": true\n}\n',
    },
    {
      name: 'middle property with a trailing single-line block comment',
      source:
        '{\n  "strict": true,\n  "declaration": true, /* generated */\n  "isolatedModules": true\n}\n',
      expected: '{\n  "strict": true,\n  "isolatedModules": true\n}\n',
    },
    {
      name: 'last property without a trailing comma and with a block comment',
      source:
        '{\n  "strict": true,\n  "declaration": true /* generated */\n}\n',
      expected: '{\n  "strict": true\n}\n',
    },
    {
      name: 'trailing line comment with horizontal whitespace',
      source:
        '{\n  "strict": true,\n  "declaration": true,    // generated    \n  "isolatedModules": true\n}\n',
      expected: '{\n  "strict": true,\n  "isolatedModules": true\n}\n',
    },
  ])(
    'deletes a line-aligned property and its $name',
    ({ expected, source }) => {
      expect(removeProperty(source, ['declaration'])).toBe(expected);
    },
  );

  it('keeps a multiline trailing block comment when line ownership is ambiguous', () => {
    const source =
      '{\n  "strict": true,\n  "declaration": true, /* generated\n  declaration */\n  "isolatedModules": true\n}\n';

    expect(removeProperty(source, ['declaration'])).toBe(
      '{\n  "strict": true,\n   /* generated\n  declaration */\n  "isolatedModules": true\n}\n',
    );
  });

  it('removes an inline comment between the value and comma without expanding compact JSONC', () => {
    const source =
      '{"strict":true,"declaration":true/* generated */,"isolatedModules":true}';

    expect(removeProperty(source, ['declaration'])).toBe(
      '{"strict":true,"isolatedModules":true}',
    );
  });

  it('preserves a compact comment after the deleted property comma', () => {
    const source =
      '{"strict":true,"declaration":true,/* next sibling rationale */"isolatedModules":true}';

    expect(removeProperty(source, ['declaration'])).toBe(
      '{"strict":true,/* next sibling rationale */"isolatedModules":true}',
    );
  });
});
