import { LIMINA_CHECK_ISSUE_CODES } from '../codes';
import { FALLBACK_CONTRACT_TEST, FAULT_FIXTURE_TEST } from './shared';
import type { PartialDetectorCoverageRegistry } from './types';

export const RELEASE_DETECTOR_COVERAGE: PartialDetectorCoverageRegistry = {
  [LIMINA_CHECK_ISSUE_CODES.releaseCheckFailed]: {
    kind: 'fault-injection',
    producers: [
      'packages/limina/src/check-reporting/codes.ts#DEFAULT_ISSUE_CODE_BY_TASK',
      'packages/limina/src/commands/release/command-result.ts#createReleaseFailureIssue',
      'packages/limina/src/execution/task-execution.ts#createInfrastructureIssue',
    ],
    task: 'release:check',
    tests: [
      FALLBACK_CONTRACT_TEST,
      'packages/limina/fixtures/detectors/fault-injection/release-check-throw/case.mts',
      FAULT_FIXTURE_TEST,
    ],
  },
  [LIMINA_CHECK_ISSUE_CODES.releaseConsistency]: {
    kind: 'planned',
    producers: [
      'packages/limina/src/check-reporting/codes.ts#releaseConsistency',
    ],
    reason:
      'Registered planned compatibility code; current typed Release producers intentionally do not emit it.',
    task: 'release:check',
  },
  [LIMINA_CHECK_ISSUE_CODES.releaseContentHash]: {
    kind: 'fixture',
    producers: [
      'packages/limina/src/package-check/release/consistency/findings.ts#addContentHashFinding',
      'packages/limina/src/package-check/release/workspace/published.ts#verifyWorkspacePackagePublished',
    ],
    task: 'release:check',
    tests: [
      'packages/limina/fixtures/detectors/release/content-hash-changed/case.mts',
      'packages/limina/fixtures/detectors/release/content-hash-config-invalid-baseline-tag/case.mts',
      'packages/limina/fixtures/detectors/release/content-hash-config-invalid-ignore/case.mts',
      'packages/limina/fixtures/detectors/release/content-hash-local-only/case.mts',
      'packages/limina/fixtures/detectors/release/content-hash-remote-only/case.mts',
      'packages/limina/fixtures/detectors/release/content-hash-user-ignore-non-match/case.mts',
      'packages/limina/integration/tests/detector-fixtures.spec.ts',
      'packages/limina/src/__tests__/release-findings.spec.ts',
      'packages/limina/src/__tests__/package.spec.ts',
    ],
  },
  [LIMINA_CHECK_ISSUE_CODES.releasePackedManifest]: {
    kind: 'fixture',
    producers: [
      'packages/limina/src/commands/release/entry.ts#collectOutputManifestFindings',
      'packages/limina/src/package-check/release/consistency/findings.ts#addPackedManifestFinding',
      'packages/limina/src/package-check/release/workspace/dependencies.ts#visitWorkspacePackageDependencies',
      'packages/limina/src/package-check/release/packed/json.ts#validatePackedManifestLint',
      'packages/limina/src/package-check/release/packed/manifest.ts#validatePackedManifest',
    ],
    task: 'release:check',
    tests: [
      'packages/limina/fixtures/detectors/release/packed-dependency-missing/case.mts',
      'packages/limina/fixtures/detectors/release/packed-dependency-range-mismatch/case.mts',
      'packages/limina/fixtures/detectors/release/packed-manifest-lint/case.mts',
      'packages/limina/fixtures/detectors/release/packed-output-catalog-specifier/case.mts',
      'packages/limina/fixtures/detectors/release/packed-output-file-specifier/case.mts',
      'packages/limina/fixtures/detectors/release/packed-output-link-specifier/case.mts',
      'packages/limina/fixtures/detectors/release/packed-output-workspace-specifier/case.mts',
      'packages/limina/fixtures/detectors/release/packed-source-link-dependency/case.mts',
      'packages/limina/fixtures/detectors/release/packed-source-private-dependency/case.mts',
      'packages/limina/fixtures/detectors/release/packed-source-workspace-dependency-missing/case.mts',
      'packages/limina/integration/tests/detector-fixtures.spec.ts',
      'packages/limina/src/__tests__/release-findings.spec.ts',
      'packages/limina/src/__tests__/package.spec.ts',
    ],
  },
  [LIMINA_CHECK_ISSUE_CODES.releaseRegistry]: {
    kind: 'external-tool',
    producers: [
      'packages/limina/src/package-check/release/consistency/findings.ts#addRegistryFinding',
      'packages/limina/src/package-check/release/registry/metadata.ts#fetchRegistryPackageMetadata',
      'packages/limina/src/package-check/release/registry/tarball.ts#fetchRegistryTarball',
      'packages/limina/src/package-check/release/workspace/published.ts#verifyWorkspacePackagePublished',
    ],
    task: 'release:check',
    tests: [
      'packages/limina/fixtures/detectors/release/registry-comparison-failed/case.mts',
      'packages/limina/fixtures/detectors/release/registry-dist-tag-missing/case.mts',
      'packages/limina/fixtures/detectors/release/registry-integrity-invalid/case.mts',
      'packages/limina/fixtures/detectors/release/registry-integrity-mismatch/case.mts',
      'packages/limina/fixtures/detectors/release/registry-integrity-missing/case.mts',
      'packages/limina/fixtures/detectors/release/registry-integrity-priority/case.mts',
      'packages/limina/fixtures/detectors/release/registry-metadata-body-read/case.mts',
      'packages/limina/fixtures/detectors/release/registry-metadata-http-status/case.mts',
      'packages/limina/fixtures/detectors/release/registry-metadata-invalid-json/case.mts',
      'packages/limina/fixtures/detectors/release/registry-metadata-invalid-object/case.mts',
      'packages/limina/fixtures/detectors/release/registry-metadata-request/case.mts',
      'packages/limina/fixtures/detectors/release/registry-metadata-timeout/case.mts',
      'packages/limina/fixtures/detectors/release/registry-package-not-found/case.mts',
      'packages/limina/fixtures/detectors/release/registry-shasum-invalid/case.mts',
      'packages/limina/fixtures/detectors/release/registry-shasum-mismatch/case.mts',
      'packages/limina/fixtures/detectors/release/registry-tarball-body-read/case.mts',
      'packages/limina/fixtures/detectors/release/registry-tarball-http-status/case.mts',
      'packages/limina/fixtures/detectors/release/registry-tarball-request/case.mts',
      'packages/limina/fixtures/detectors/release/registry-tarball-timeout/case.mts',
      'packages/limina/fixtures/detectors/release/registry-tarball-url-missing/case.mts',
      'packages/limina/fixtures/detectors/release/registry-version-missing/case.mts',
      'packages/limina/integration/tests/detector-fixtures.spec.ts',
      'packages/limina/src/__tests__/release-findings.spec.ts',
      'packages/limina/src/__tests__/package.spec.ts',
    ],
  },
  [LIMINA_CHECK_ISSUE_CODES.releaseTarballHygiene]: {
    kind: 'fixture',
    producers: [
      'packages/limina/src/commands/release/entry.ts#runReleaseCheckEntry',
      'packages/limina/src/package-check/release/consistency/findings.ts#addTarballHygieneFinding',
      'packages/limina/src/package-check/release/packed/json.ts#readPackedPackageJson',
      'packages/limina/src/package-check/release/tarball-hygiene.ts#validateReleaseTarballHygiene',
    ],
    task: 'release:check',
    tests: [
      'packages/limina/fixtures/detectors/release/tarball-license-missing/case.mts',
      'packages/limina/fixtures/detectors/release/tarball-output-private/case.mts',
      'packages/limina/fixtures/detectors/release/tarball-readme-missing/case.mts',
      'packages/limina/fixtures/detectors/release/tarball-source-map/case.mts',
      'packages/limina/fixtures/detectors/release/tarball-source-mapping-url/case.mts',
      'packages/limina/integration/tests/detector-fixtures.spec.ts',
      'packages/limina/src/__tests__/release-findings.spec.ts',
      'packages/limina/src/__tests__/package.spec.ts',
    ],
  },
} satisfies PartialDetectorCoverageRegistry;
